name: Azure CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: self-hosted  # Replace 'self-hosted' with the label of your Azure VM runner.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add any additional steps required for your build process (e.g., build, test, etc.)

      - name: Log in to Azure Container Registry
        run: |
          az account set --subscription="${AZURE_SUBSCRIPTION_ID}"
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az acr login --name acrsummarizer

      - name: Build and Push Docker Image to Azure Container Registry
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          IMAGE_TAG: latest
        run: |
          # Log in to Azure Container Registry
          az acr login --name $ACR_LOGIN_SERVER --username $ACR_USERNAME --password $ACR_PASSWORD

          # Build your Docker container
          docker build -t $ACR_LOGIN_SERVER/acrsummarizer:$IMAGE_TAG .

          # Push the image to ACR
          docker push $ACR_LOGIN_SERVER/acrsummarizer:$IMAGE_TAG

          echo "::set-output name=image::$ACR_LOGIN_SERVER/acrsummarizer:$IMAGE_TAG"

  continuous-deployment:
    name: Deploy to Azure VM
    needs: build-and-push-image
    runs-on: self-hosted  # Replace 'self-hosted' with the label of your Azure VM runner.

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Copy Docker Image to Azure VM
        run: |
          docker save -o image.tar acrsummarizer.azurecr.io/acrsummarizer:latest
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null image.tar azureadmin@20.172.222.50:~/image.tar

      - name: SSH into Azure VM and Load Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null azureadmin@20.172.222.50 'docker load -i ~/image.tar'

      - name: Run Docker Container on Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null azureadmin@20.172.222.50 'docker run -d -p 8080:8080 --name acrsummarizer acrsummarizer.azurecr.io/acrsummarizer:latest'
